server:
  port: 9001

spring:
  application:
    name: cloud-jskj-payment
  cloud:
    nacos:
      discovery:
       # server-addr: 192.168.6.4:1111 linux集群
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
      datasource:     #持久化sentinel配置
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: cloud-jskj-payment
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
    

management:
  endpoints:
    web:
      exposure:
        include: '*'  #监控
feign:
  sentinel:
    enabled: true #激活Sentinel 对Feign的支持

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath*:mapper/*.xml